---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: mysql-sc
    labels:
        app: mysql
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pvc
    labels:
        app: mysql
spec:
    storageClassName: mysql-sc
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deploy
    labels:
        app: mysql
spec:
    selector:
        matchLabels:
            app: mysql
    replicas: 1
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
            - name: mysql
              image: mysql:1
              imagePullPolicy: Never
              ports:
                - containerPort: 3306
              volumeMounts:
               - name: mysql-pv
                 mountPath: /var/lib/mysql
            volumes:
            - name: mysql-pv
              persistentVolumeClaim:
                claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-svc
    labels:
        app: mysql
spec:
    clusterIP: 10.108.205.191
    selector:
        app: mysql
    ports:
    - port: 3306
