---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pvc
    labels:
        app: mysql
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deploy
    labels:
        app: mysql
spec:
    selector:
        matchLabels:
            app: mysql
    replicas: 1
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
            - name: mysql
              image: mysql:1
              imagePullPolicy: Never
              ports:
                - containerPort: 3306
              livenessProbe:
                exec:
                  command:
                  - sh
                  - /tmp/check.sh
                initialDelaySeconds: 30
                periodSeconds: 5
                timeoutSeconds: 5
              volumeMounts:
               - name: mysql-pv
                 mountPath: /var/lib/mysql
            volumes:
            - name: mysql-pv
              persistentVolumeClaim:
                claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-svc
    labels:
        app: mysql
spec:
    clusterIP: 10.108.205.191
    selector:
        app: mysql
    ports:
    - port: 3306
