apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deploy
    labels:
        app: nginx
spec:
    selector:
        matchLabels:
            app: nginx
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx:1
              imagePullPolicy: Never
              ports:
              - containerPort: 80
                name: http
              - containerPort: 443
                name: https
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-svc
    annotations:
        metallb.universe.tf/allow-shared-ip: shared
    labels:
        app: nginx
spec:
    type: LoadBalancer
    selector:
        app: nginx
    ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
