---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: phpmyadmin-deploy
    labels:
        app: phpmyadmin
spec:
    selector:
        matchLabels:
            app: phpmyadmin
    replicas: 1
    template:
        metadata:
            labels:
                app: phpmyadmin
        spec:
            containers:
            - name: phpmyadmin
              image: phpmyadmin:1
              imagePullPolicy: Never
              ports:
              - containerPort: 5000
              livenessProbe:
                exec:
                  command:
                  - sh
                  - /tmp/check.sh
                initialDelaySeconds: 20
                periodSeconds: 10
                timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-svc
    annotations:
        metallb.universe.tf/allow-shared-ip: shared
    labels:
        app: phpmyadmin
spec:
    selector:
        app: phpmyadmin
    type: LoadBalancer
    ports:
    - port: 5000
      protocol: TCP
