apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deploy
spec:
    selector:
        matchLabels:
            run: nginx
    replicas: 2
    template:
        metadata:
            labels:
                run: nginx
        spec:
            containers:
            - name: nginx-pod
              image: nginx:v1.0.0
              imagePullPolicy: Never
              ports:
              - containerPort: 80
                name: http
              - containerPort: 443
                name: https

---
apiVersion: v1
kind: Service
metadata:
    name: nginx-svc
    labels:
        run: nginx
spec:
    type: LoadBalancer
    selector:
        run: nginx
    ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
