---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wordpress-pvc
    labels:
        app: wordprss
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress-deploy
    labels:
        app: wordpress
spec:
    selector:
        matchLabels:
            app: wordpress
    replicas: 1
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
            - name: wordpress
              image: wordpress:1
              imagePullPolicy: Never
              env:
                - name: DB_NAME
                  value: "wordpress_db"
                - name: DB_HOST
                  value: mysql-svc:3306
                # - name: DB_PORT
                #   value: "3306"
                - name: DB_USER
                  value: "admin"
                - name: DB_PASSWORD
                  valueFrom:
                      secretKeyRef:
                          name: mysql-pass
                          key: password
              ports:
                - containerPort: 5050
              volumeMounts:
                - name: wordpress-pv
                  mountPath: /var/www
            volumes:
            - name: wordpress-pv
              persistentVolumeClaim:
                  claimName: wordpress-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: wordpress-svc
    annotations:
        metallb.universe.tf/allow-shared-ip: 192.168.99.95
    labels:
        app: wordpress
spec:
    selector:
        app: wordpress
    type: LoadBalancer
    loadBalancerIP: 192.168.99.95
    ports:
    - port: 5050
      protocol: TCP
