---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress-deploy
    labels:
        app: wordpress
spec:
    selector:
        matchLabels:
            app: wordpress
    replicas: 1
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
            - name: wordpress
              image: wordpress:1
              imagePullPolicy: Never
              ports:
                - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
    name: wordpress-svc
    annotations:
        metallb.universe.tf/allow-shared-ip: 192.168.99.95
    labels:
        app: wordpress
spec:
    selector:
        app: wordpress
    type: LoadBalancer
    loadBalancerIP: 192.168.99.95
    ports:
    - port: 5050
      protocol: TCP
